force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Broker__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PropertyUtility.cls
public class PropertyUtility {
	public static void newListedProperties()
    {
        List<Property__c>newPropList = [SELECT Name,Broker__r.Email__c,Days_On_Market__c FROM Property__c WHERE Days_On_Market__c < 31];
        for(Property__C pro:newPropList)
        {
            String propEmail = 'Address:'+pro.Name+':'+pro.Broker__r.Email__C;
            system.debug(propEmail);
        }
    }
}